# Generated by Django 3.0.7 on 2020-08-12 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=75, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Only letters are allowed.')])),
                ('nim_tpb', models.IntegerField(default=16519599, validators=[django.core.validators.MaxValueValidator(16519600), django.core.validators.MinValueValidator(16519000)])),
                ('nim_jurusan', models.IntegerField(default=13519999)),
                ('panggilan', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Only letters are allowed.')])),
                ('jenis_kelamin', models.CharField(choices=[('FEMALE', 'Perempuan'), ('MALE', 'Laki-laki')], max_length=6)),
                ('jurusan', models.CharField(choices=[('IF', 'Teknik Informatika'), ('STI', 'Sistem Teknologi Informasi')], max_length=3)),
                ('image', models.ImageField(default='default.png', upload_to='asyncpics')),
            ],
        ),
    ]
