# Generated by Django 3.0.7 on 2020-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_person_kelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jenis_kelamin',
            field=models.CharField(choices=[('PEREMPUAN', 'Perempuan'), ('LAKI-LAKI', 'Laki-laki')], max_length=9),
        ),
    ]
