# Generated by Django 3.0.7 on 2020-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200813_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.png', upload_to='async'),
        ),
    ]
